"""
Django settings for meatze_site project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""



from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from dotenv import load_dotenv

load_dotenv(BASE_DIR / ".env")  # BASE_DIR уже у тебя есть выше

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "0") == "1"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS") else []

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

TIME_ZONE = "Europe/Madrid"
USE_TZ = True

# Application definition
ASGI_APPLICATION = "meatze_site.asgi.application"
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    "api",
    "channels",
    "panel",
    "api.videos",
    "panel.shortshare",
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")]},
    }
}

ROOT_URLCONF = 'meatze_site.urls'
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/alumno/'
MEATZE_BASE_URL = "https://meatzeaula.es"
MEATZE_ADMIN_URL_PATH = "/admin-panel/"  
MEATZE_ASSISTANT_INDEX_PATH = "docs/autogen_strict/assistant_index.json"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
	'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meatze_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", ""),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

# MEATZE admin panel password
MEATZE_ADMIN_PASS = os.getenv("MEATZE_ADMIN_PASS", "")

CSRF_TRUSTED_ORIGINS = [
    "https://meatzed.zaindari.eus",
]

MEATZE_DOCX_LOGOS = {
    "lanbide": "/home/iaadmin/meatze/files/lanbide.png",
    "euskadi": "/home/iaadmin/meatze/files/euskadi.png",
    "eu":      "/home/iaadmin/meatze/files/eu.png",
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "1") == "1"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "MEATZE Admin <noreply@example.com>")

BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = BASE_DIR / "files"
MEDIA_URL = "/files/"

STATIC_URL = "/static/"

# Куда collectstatic складывает "собранные" файлы (должна быть отдельная папка)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Где лежат исходные статические файлы проекта (твои /static)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


WA_TOKEN = os.getenv("WA_TOKEN", "")
WA_PHONE_ID = os.getenv("WA_PHONE_ID", "")
WA_VERIFY_TOKEN = os.getenv("WA_VERIFY_TOKEN", "")
WA_ADMIN_BILBAO = os.getenv("WA_ADMIN_BILBAO", "")
WA_ADMIN_BARAKALDO = os.getenv("WA_ADMIN_BARAKALDO", "")

# LAN школы (подставь свои сети)
MZ_SCHOOL_LAN_CIDRS = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "192.168.1.0/16",
    "192.168.2.0/16",
    "188.65.0.0/16",
    "176.28.0.0/16",
    # если у тебя бывает 100.64.0.0/10 (CGNAT) внутри — можно добавить:
    # "100.64.0.0/10",
]

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024      # 10MB (можно меньше/больше)
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024 * 1024 # 6GB общий лимит тела запроса (пример)

MZ_ATTENDANCE_HB_SEC = 90   

PLAYWRIGHT_BIN = "/usr/bin/chromium"  # или оставь пустым, если playwright сам

JITSI_DOMAIN = "meetjwt.meatzeaula.es"
JITSI_JWT_ENABLED = True
JITSI_JWT_SECRET = "meatze123"          # то же самое что app_secret в Prosody
JITSI_JWT_APP_ID = "meatze"             # то же что app_id
JITSI_JWT_AUD = "jitsi"

MEETZE_SHOW_LIVE_TAB = True
X_FRAME_OPTIONS = "SAMEORIGIN"

LOGGING = {
  "version": 1,
  "disable_existing_loggers": False,
  "handlers": {"console": {"class": "logging.StreamHandler"}},
  "loggers": {
    "jitsi": {"handlers": ["console"], "level": "WARNING"},
  }
}

CSRF_TRUSTED_ORIGINS = [
    "https://meatzeaula.es",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

