# Generated by Django 6.0 on 2025-12-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_enrol_unique_together_curso_horas_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MZSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
    ]
