# Generated by Django 6.0 on 2025-12-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mzsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia', 'hora_inicio']},
        ),
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='horario',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.curso'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='modulo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
