# Generated by Django 6.0 on 2025-12-07 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_horario_options_horario_grupo_horario_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'code', 'created_at'], name='api_loginpi_email_860e07_idx')],
            },
        ),
    ]
