# Generated by Django 6.0 on 2025-12-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_loginpin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginpin',
            name='api_loginpi_email_860e07_idx',
        ),
        migrations.AlterField(
            model_name='loginpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
