# Generated by Django 6.0 on 2025-12-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_loginpin_api_loginpi_email_860e07_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpin',
            name='code',
        ),
        migrations.RemoveField(
            model_name='loginpin',
            name='used',
        ),
        migrations.AddField(
            model_name='loginpin',
            name='pin',
            field=models.CharField(db_index=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='loginpin',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
