# Generated by Django 6.0 on 2025-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatmessage_chatreaction_chatread'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa', models.CharField(max_length=32, unique=True, verbose_name='Número WhatsApp')),
                ('name', models.CharField(blank=True, default='', max_length=190, verbose_name='Nombre')),
                ('loc', models.CharField(blank=True, default='', max_length=64, verbose_name='Localidad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WA contact',
                'verbose_name_plural': 'WA contacts',
                'db_table': 'meatze_subs_wa',
            },
        ),
    ]
