# Generated by Django 6.0 on 2025-12-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wacontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wacontact',
            name='loc',
            field=models.CharField(blank=True, choices=[('Bilbao', 'Bilbao'), ('Barakaldo', 'Barakaldo')], default='', max_length=50, verbose_name='Localidad'),
        ),
        migrations.CreateModel(
            name='WaInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=190)),
                ('source', models.CharField(default='meatze', max_length=20)),
                ('msg', models.TextField()),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meatze_wa_inbox',
                'indexes': [models.Index(fields=['wa'], name='meatze_wa_i_wa_0cbd03_idx'), models.Index(fields=['source'], name='meatze_wa_i_source_e284ea_idx'), models.Index(fields=['direction'], name='meatze_wa_i_directi_25b088_idx'), models.Index(fields=['created_at'], name='meatze_wa_i_created_a41dc6_idx')],
            },
        ),
    ]
