# Generated by Django 6.0 on 2025-12-12 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_wacontact_loc_wainbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('requested_role', models.CharField(choices=[('unknown', 'Unknown'), ('teacher', 'Teacher'), ('student', 'Student')], default='unknown', max_length=20)),
                ('decided_role', models.CharField(choices=[('unknown', 'Unknown'), ('teacher', 'Teacher'), ('student', 'Student')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='api_pending_email_cbd9c8_idx'), models.Index(fields=['status'], name='api_pending_status_99b3d8_idx'), models.Index(fields=['created_at'], name='api_pending_created_842982_idx')],
            },
        ),
    ]
