# Generated by Django 6.0 on 2025-12-17 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pendingrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatread',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('course', 'Course'), ('dm', 'Direct')], db_index=True, default='course', max_length=16),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread_key',
            field=models.CharField(db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_dm_inbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatread',
            name='kind',
            field=models.CharField(choices=[('course', 'Course'), ('dm', 'Direct')], db_index=True, default='course', max_length=16),
        ),
        migrations.AddField(
            model_name='chatread',
            name='peer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_reads_peer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatread',
            name='codigo',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['codigo', 'kind', 'created_at'], name='api_chatmes_codigo_6a3134_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread_key', 'created_at'], name='api_chatmes_thread__5b5297_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['codigo', 'kind', 'id'], name='api_chatmes_codigo_6e2da2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatread',
            index=models.Index(fields=['codigo', 'kind'], name='api_chatrea_codigo_8724f3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatread',
            index=models.Index(fields=['user', 'codigo', 'kind'], name='api_chatrea_user_id_57a993_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'course'), ('to_user__isnull', True)), models.Q(('kind', 'course'), _negated=True), _connector='OR'), name='chatmsg_course_to_user_null'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'dm'), ('to_user__isnull', False)), models.Q(('kind', 'dm'), _negated=True), _connector='OR'), name='chatmsg_dm_to_user_not_null'),
        ),
        migrations.AddConstraint(
            model_name='chatread',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'course'), ('peer_user__isnull', True)), fields=('codigo', 'user', 'kind'), name='uniq_chatread_course'),
        ),
        migrations.AddConstraint(
            model_name='chatread',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'dm'), ('peer_user__isnull', False)), fields=('codigo', 'user', 'kind', 'peer_user'), name='uniq_chatread_dm'),
        ),
        migrations.AddConstraint(
            model_name='chatread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'course'), ('peer_user__isnull', True)), models.Q(('kind', 'course'), _negated=True), _connector='OR'), name='chatread_course_peer_null'),
        ),
        migrations.AddConstraint(
            model_name='chatread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'dm'), ('peer_user__isnull', False)), models.Q(('kind', 'dm'), _negated=True), _connector='OR'), name='chatread_dm_peer_not_null'),
        ),
    ]
