# Generated by Django 6.0 on 2025-12-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_chatread_unique_together_chatmessage_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo_formacion',
            field=models.CharField(blank=True, choices=[('ocupacion', 'Ocupación'), ('continuacion', 'Continuación')], default='', max_length=20),
        ),
    ]
