# Generated by Django 6.0 on 2025-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_curso_tipo_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_formacion',
            field=models.CharField(blank=True, choices=[('ocupacional', 'Ocupacional'), ('continua', 'Continua')], default='', max_length=20),
        ),
    ]
