# Generated by Django 6.0 on 2025-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_curso_tipo_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_formacion',
            field=models.CharField(blank=True, choices=[('ocupacion', 'Ocupacional'), ('continuacion', 'Continua')], default='', max_length=20),
        ),
    ]
