# Generated by Django 6.0 on 2026-01-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_curso_tipo_formacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_codigo', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('seq', models.PositiveIntegerField(default=0)),
                ('event', models.CharField(db_index=True, max_length=50)),
                ('object_type', models.CharField(blank=True, default='', max_length=50)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('page', models.CharField(blank=True, default='', max_length=200)),
                ('ref', models.CharField(blank=True, default='', max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('delta_sec', models.PositiveIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['curso_codigo', 'user', '-created_at'], name='api_learnin_curso_c_f2d68e_idx'), models.Index(fields=['session_id', 'user', '-created_at'], name='api_learnin_session_997dda_idx'), models.Index(fields=['event', '-created_at'], name='api_learnin_event_0f4adc_idx')],
            },
        ),
    ]
