# Generated by Django 6.0 on 2026-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_learningevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wa',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
