# Generated by Django 6.0 on 2026-02-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_wa'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='live_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='live_is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='live_last_signal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='live_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
