# Generated by Django 6.0 on 2026-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_curso_live_closed_at_curso_live_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nonlective_years',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='curso',
            name='use_global_nonlective',
            field=models.BooleanField(default=True),
        ),
    ]
