# Generated by Django 6.0 on 2025-12-08 19:54

import django.db.models.deletion
import panel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_remove_loginpin_code_remove_loginpin_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alumnos', 'Para alumnos'), ('docentes', 'Docentes'), ('privado', 'Privados (míos)')], default='alumnos', max_length=10)),
                ('module_key', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=panel.models.curso_file_upload_path)),
                ('size', models.PositiveIntegerField(default=0)),
                ('ext', models.CharField(blank=True, max_length=16)),
                ('share_alumnos', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.curso')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
