# Generated by Django 6.0 on 2025-12-09 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_loginpin_code_remove_loginpin_used_and_more'),
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=8)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_accesses', to='api.curso')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'curso', 'temp_name')},
            },
        ),
    ]
