# Generated by Django 6.0 on 2025-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_tempaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursofile',
            name='module_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
