# Generated by Django 6.0 on 2025-12-16 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pendingrole'),
        ('panel', '0003_alter_cursofile_module_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_downloads', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='panel.cursofile')),
            ],
            options={
                'indexes': [models.Index(fields=['file', 'alumno'], name='panel_mater_file_id_d3d570_idx'), models.Index(fields=['alumno', '-downloaded_at'], name='panel_mater_alumno__00d44f_idx')],
                'constraints': [models.UniqueConstraint(fields=('file', 'alumno'), name='uniq_file_download_per_alumno')],
            },
        ),
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50)),
                ('item_label', models.CharField(blank=True, default='', max_length=120)),
                ('received', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_receipts', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.curso')),
            ],
            options={
                'indexes': [models.Index(fields=['curso', 'alumno', 'item_key'], name='panel_mater_curso_i_4c3099_idx')],
                'constraints': [models.UniqueConstraint(fields=('curso', 'alumno', 'item_key'), name='uniq_receipt_item_per_course')],
            },
        ),
    ]
