# Generated by Django 6.0 on 2026-01-14 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_learningevent'),
        ('panel', '0004_materialdownload_materialreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoPhysicalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_keys', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_cfg', to='api.curso')),
            ],
        ),
    ]
