# Generated by Django 6.0 on 2026-01-15 11:31

import django.db.models.deletion
import django.utils.timezone
import panel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_learningevent'),
        ('panel', '0005_cursophysicalconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=panel.models.task_upload_path)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('ext', models.CharField(blank=True, default='', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.curso')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=panel.models.submission_upload_path)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('ext', models.CharField(blank=True, default='', max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Entregado'), ('graded', 'Calificado')], default='submitted', max_length=12)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_task_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='panel.coursetask')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('task', 'alumno'), name='uniq_submission_per_task_alumno')],
            },
        ),
    ]
