# Generated by Django 6.0 on 2026-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_coursetask_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
