# Generated by Django 6.0 on 2026-01-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='active_confirmed_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='active_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
