# Generated by Django 6.0 on 2026-01-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_learningevent'),
        ('panel', '0010_attendancesession_active_confirmed_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='api.horario'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lesson_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lesson_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lesson_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
