# Generated by Django 6.0 on 2026-01-19 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_wa'),
        ('panel', '0011_attendancesession_horario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancesession',
            name='panel_atten_curso_c_d28d4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancesession',
            name='panel_atten_user_id_fdef48_idx',
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['curso_codigo', 'horario', 'status'], name='panel_atten_curso_c_b7696c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['curso_codigo', 'horario', 'started_at'], name='panel_atten_curso_c_5c1e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['user', 'curso_codigo', 'horario'], name='panel_atten_user_id_8dcc54_idx'),
        ),
    ]
