# Generated by Django 6.0 on 2026-01-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_wa'),
        ('panel', '0012_remove_attendancesession_panel_atten_curso_c_d28d4f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoPhysicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_items', to='api.curso')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('curso', 'key')},
            },
        ),
    ]
