# Generated by Django 6.0 on 2026-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_cursophysicalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='module_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='module_label',
            field=models.CharField(blank=True, default='', max_length=190),
        ),
    ]
