# Generated by Django 6.0 on 2026-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_coursetask_module_key_coursetask_module_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='convocatoria',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1ª'), (2, '2ª')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='is_final_exam',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
