# Generated by Django 6.0 on 2026-02-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_coursetask_convocatoria_coursetask_is_final_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursofile',
            name='folder_path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
    ]
