# Generated by Django 6.0 on 2026-02-13 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_wa'),
        ('panel', '0017_cursofolder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(db_index=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='api.curso')),
            ],
            options={
                'indexes': [models.Index(fields=['curso', 'alumno'], name='panel_stude_curso_i_48de83_idx'), models.Index(fields=['curso', 'module_key'], name='panel_stude_curso_i_da1dcb_idx')],
                'constraints': [models.UniqueConstraint(fields=('curso', 'alumno', 'module_key'), name='uniq_mod_access')],
            },
        ),
    ]
