# Generated by Django 6.0 on 2026-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_studentmoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursofile',
            name='is_visible_to_students',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
