# Generated by Django 6.0 on 2026-03-04 20:57

import django.db.models.deletion
import panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_cursofile_is_visible_to_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=panel.models.task_attach_upload_path)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('ext', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='panel.coursetask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
