# Generated by Django 6.0 on 2026-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_coursetaskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursofile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
