# Generated by Django 6.0 on 2026-03-10 08:39

import django.db.models.deletion
import panel.models_generation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_alter_cursofile_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(upload_to=panel.models_generation.generation_upload_to)),
                ('result_file', models.FileField(blank=True, null=True, upload_to=panel.models_generation.generation_result_to)),
                ('prompt', models.TextField()),
                ('seconds', models.PositiveIntegerField(default=8)),
                ('quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('orig_width', models.PositiveIntegerField(default=0)),
                ('orig_height', models.PositiveIntegerField(default=0)),
                ('fit_width', models.PositiveIntegerField(default=0)),
                ('fit_height', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='new', max_length=16)),
                ('comfy_prompt_id', models.CharField(blank=True, default='', max_length=128)),
                ('comfy_client_id', models.CharField(blank=True, default='', max_length=128)),
                ('seed', models.BigIntegerField(default=0)),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
