# Generated by Django 6.0 on 2026-03-10 09:40

import django.db.models.deletion
import panel.models_generation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_videogenerationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='job_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', max_length=16),
        ),
        migrations.CreateModel(
            name='ImageGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image_1', models.ImageField(upload_to=panel.models_generation.generation_upload_to)),
                ('source_image_2', models.ImageField(blank=True, null=True, upload_to=panel.models_generation.generation_upload_to)),
                ('source_image_3', models.ImageField(blank=True, null=True, upload_to=panel.models_generation.generation_upload_to)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to=panel.models_generation.generation_result_to)),
                ('prompt', models.TextField()),
                ('quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('status', models.CharField(default='new', max_length=16)),
                ('comfy_prompt_id', models.CharField(blank=True, default='', max_length=128)),
                ('comfy_client_id', models.CharField(blank=True, default='', max_length=128)),
                ('seed', models.BigIntegerField(default=0)),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
