# Generated by Django 6.0 on 2026-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_videogenerationjob_job_type_imagegenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='aspect_ratio',
            field=models.CharField(choices=[('original', 'Original'), ('16:9', '16:9')], default='original', max_length=20),
        ),
    ]
