# Generated by Django 6.0 on 2026-03-10 10:09

import django.db.models.deletion
import panel.models_generation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_videogenerationjob_aspect_ratio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegenerationjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='imagegenerationjob',
            name='source_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=panel.models_generation.generation_upload_to),
        ),
        migrations.AlterField(
            model_name='imagegenerationjob',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='source_image',
            field=models.ImageField(blank=True, null=True, upload_to=panel.models_generation.generation_upload_to),
        ),
        migrations.CreateModel(
            name='GenerationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=panel.models_generation.generation_asset_to)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=16)),
                ('origin', models.CharField(choices=[('upload', 'Upload'), ('generated', 'Generated')], default='upload', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='result_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_result_jobs', to='panel.generationasset'),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='source_asset_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_image_ref_1', to='panel.generationasset'),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='source_asset_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_image_ref_2', to='panel.generationasset'),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='source_asset_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_image_ref_3', to='panel.generationasset'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='last_frame_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_last_frame_jobs', to='panel.generationasset'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='result_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_result_jobs', to='panel.generationasset'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_video_jobs', to='panel.generationasset'),
        ),
    ]
