# Generated by Django 6.0 on 2026-02-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_owner_playlist_playlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=16)),
                ('path', models.CharField(help_text='Напр.: /acceder/ или /alumno/curso/*/', max_length=255)),
                ('query_contains', models.CharField(blank=True, default='', help_text='Напр.: tab=materiales или tab=live. Оставь пустым если не нужно.', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Меньше = важнее')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_bindings', to='videos.playlist')),
                ('start_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['role', 'is_active', 'priority'], name='videos_help_role_bdb661_idx'), models.Index(fields=['path'], name='videos_help_path_5dfa69_idx')],
            },
        ),
    ]
