# Generated by Django 6.0 on 2026-02-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_helpbinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpbinding',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='helpbinding',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='helpbinding',
            name='query_contains',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
