# Generated by Django 6.0 on 2026-02-13 07:32

import django.core.validators
import django.db.models.deletion
import panel.shortshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator()])),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=panel.shortshare.models.default_link_expires)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='shortshare.shortroom')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'expires_at'], name='shortshare__room_id_6d441b_idx')],
            },
        ),
    ]
